### ISSUE TITLE
投稿エラー

### ISSUE THREAD

**Issue by mkachan1** [tetsuyaohira/rakuten-room-auto-post#3]
初めまして。
コードを使わせていただいているのですが、
スクレイピングのところで、ID,パスワード入力後、
投稿画面のセレクター表示を待つところでタイムアウトになります。
CHATGPTから商品説明を引っぱってくるところはうまく動いています。
自分なりに色々やっていますが、スクレイピングの知識に乏しいので、
進みません。ご対応いただけると、大変うれしいです。
よろしくお願いいたします。

**Comment by tetsuyaohira** [comment]
@mkachan1 
こちらでは再現できませんでした
エラーメッセージとわかる範囲の実行環境を教えていただけますか？

**Comment by mkachan1** [comment]
お世話になります。

実行環境は、Windows10です。

エラーメッセージは、下記になります。
scrapeWebsites.tsの「ログイン後のページ遷移を待つ」のところで、collect-contentが見つからず。
タイムアウトになっているようです。

Start job:2024/4/21 10:00:00
numberToday:22
-----------------------------------------------
https://room.rakuten.co.jp/mix?itemcode=nondonkai:10000371&scid=we_room_upc60
1:2024/4/21 10:00:00
Error: TimeoutError: Waiting for selector `#collect-content` failed: Waiting failed: 30000ms exceeded
    at new WaitTask (C:\Users\user\rakuten-room-auto-post\node_modules\puppeteer-core\src\common\WaitTask.ts:92:28)
    at IsolatedWorld.waitForFunction (C:\Users\user\rakuten-room-auto-post\node_modules\puppeteer-core\src\api\Realm.ts:84:22)
    at Function.waitFor (C:\Users\user\rakuten-room-auto-post\node_modules\puppeteer-core\src\common\QueryHandler.ts:169:50)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async CdpFrame.waitForSelector (C:\Users\user\rakuten-room-auto-post\node_modules\puppeteer-core\src\api\Frame.ts:696:13)
    at async CdpPage.waitForSelector (C:\Users\user\rakuten-room-auto-post\node_modules\puppeteer-core\src\api\Page.ts:2907:12)
-----------------------------------------------

**Comment by tetsuyaohira** [comment]
scrapeWebsite.tsの17行目のUserAgentを指定している部分が怪しそうですね
```
  await page.setUserAgent(
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"
  );
```
手元にWindowsがないので、解消できるかわかりませんが、
https://testpage.jp/tool/ip_user_agent.php
の`ブラウザのユーザーエージェントーHTTP_USER_AGENT`の値で17行目を更新してみてください

**Comment by tetsuyaohira** [comment]
または、OSに応じてUserAgentを設定するように修正したので、最新のmainブランチを取り込んでみてください

**Comment by mkachan1** [comment]
ありがとうございます。やってみます。

**Comment by mkachan1** [comment]
やってみましたが、症状変わらずです。

**Comment by net0726** [comment]
ジャンル指定で実行すると私も同じエラーになりました。Windows環境です。
ちなみにジャンル指定しないと、対象ジャンルなしとなり、何も出てきません。

> ts-node index.ts genre 100283

numberToday:4
-----------------------------------------------
https://room.rakuten.co.jp/mix?itemcode=hanaechizen:10000381&scid=we_room_upc60
1:2024/6/2 8:27:05
Error: TimeoutError: Waiting for selector `#collect-content` failed: Waiting failed: 30000ms exceeded
    at new WaitTask (C:\Users\NEC-PCuser\rakuten-room-auto-post\node_modules\puppeteer-core\src\common\WaitTask.ts:92:28)
    at IsolatedWorld.waitForFunction (C:\Users\NEC-PCuser\rakuten-room-auto-post\node_modules\puppeteer-core\src\api\Realm.ts:84:22)
    at Function.waitFor (C:\Users\NEC-PCuser\rakuten-room-auto-post\node_modules\puppeteer-core\src\common\QueryHandler.ts:169:50)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async CdpFrame.waitForSelector (C:\Users\NEC-PCuser\rakuten-room-auto-post\node_modules\puppeteer-core\src\api\Frame.ts:696:13)
    at async CdpPage.waitForSelector (C:\Users\NEC-PCuser\rakuten-room-auto-post\node_modules\puppeteer-core\src\api\Page.ts:2907:12)

**Comment by denon752** [comment]
少し修正したら実行できました！
ありがとうございます。
